(() => {
  const root=document.getElementById('spatial-demo');if(!root)return;
  const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d');if(!ctx)return;
  const $=id=>document.getElementById(id),position=$('spatial-position'),frequency=$('spatial-frequency'),button=$('spatial-audio');
  const copy={fr:{notes:'À propos des trajets',eyebrow:'Audio spatial / démonstration 3D',title:'Propagation et obstacles',intro:'Le défilement déplace l’auditeur. Observez les chemins du son, puis activez l’écoute pour entendre l’effet du mur.',viewHint:'Glissez pour tourner la vue · Défilez pour avancer',direct:'Direct',diffraction:'Diffraction',reflection:'Réflexion',transmission:'Transmission',position:'Position de l’auditeur',frequency:'Fréquence de la source',straight:'Trajet rectiligne',shortest:'Contournement le plus court',wallDepth:'Traversée du mur',model:'Modèle géométrique simplifié : vitesse du son 343 m/s, filtrage et atténuation illustratifs. La réflexion repart vers la source ; le son transmis et le son diffracté rejoignent l’auditeur. L’écoute se coupe en quittant la scène.',source:'Source',listener:'Auditeur',wall:'Mur',open:'Trajet direct dégagé',blocked:'Trajet direct occulté',listen:'Écouter la scène',stop:'Couper l’écoute',failed:'Audio indisponible',canvas:'Scène 3D : source, mur et auditeur. Le curseur de position ou les flèches déplacent l’auditeur.',top:'bord supérieur',negative:'bord gauche',positive:'bord droit',clearNote:'La source est visible : le son arrive directement. En avançant derrière le mur, le trajet direct rencontre sa surface.',blockedNote:'Le mur coupe le trajet direct. Le tracé vert suit le contournement le plus court ; le tracé rose traverse le matériau avec atténuation et filtrage. Au point orange, l’angle de réflexion égale l’angle d’incidence.'},en:{notes:'About the paths',eyebrow:'Spatial audio / 3D demonstration',title:'Propagation and obstacles',intro:'Scrolling moves the listener. Observe the sound paths, then enable listening to hear the effect of the wall.',viewHint:'Drag to orbit · Scroll to move',direct:'Direct',diffraction:'Diffraction',reflection:'Reflection',transmission:'Transmission',position:'Listener position',frequency:'Source frequency',straight:'Straight path',shortest:'Shortest route around the wall',wallDepth:'Distance through the wall',model:'Simplified geometric model: sound speed 343 m/s, illustrative filtering and attenuation. Reflection returns towards the source; transmitted and diffracted sound reach the listener. Audio stops when the scene leaves view.',source:'Source',listener:'Listener',wall:'Wall',open:'Direct path clear',blocked:'Direct path occluded',listen:'Listen to the scene',stop:'Stop listening',failed:'Audio unavailable',canvas:'3D scene: source, wall and listener. The position slider or arrow keys move the listener.',top:'top edge',negative:'left edge',positive:'right edge',clearNote:'The source is visible: sound arrives directly. As the listener moves behind the wall, the direct path meets its surface.',blockedNote:'The wall blocks the direct path. Green shows the shortest route around its edges; pink passes through the material with attenuation and filtering. At the orange contact point, reflection and incidence angles are equal.'}};
  let lang=document.documentElement.lang==='en'?'en':'fr',state=SpatialSceneModel.state(0),yaw=.58,pitch=.68,w=1,h=1,visible=false,raf=0,dirty=true,lastDraw=0,drag=null,audio=null,audioError=false,audioGeneration=0,manualPosition=false;
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');
  function updateCopy(){lang=document.documentElement.lang==='en'?'en':'fr';root.querySelectorAll('[data-spatial-copy]').forEach(e=>e.textContent=copy[lang][e.dataset.spatialCopy]);canvas.setAttribute('aria-label',copy[lang].canvas);updateReadouts();requestDraw();}
  function updateReadouts(){const c=copy[lang];$('spatial-status').textContent=state.blocked?c.blocked:c.open;$('spatial-status').dataset.blocked=String(state.blocked);button.textContent=audio?c.stop:audioError?c.failed:c.listen;button.setAttribute('aria-pressed',String(!!audio));position.value=Math.round(state.progress*100);$('spatial-position-value').textContent=Math.round(state.progress*100)+' %';$('spatial-frequency-value').textContent=state.frequency+' Hz';$('spatial-straight').textContent=state.directLength.toFixed(2)+' m';$('spatial-shortest').textContent=state.blocked?state.diffraction.length.toFixed(2)+' m · '+c[state.diffraction.edge]:'—';$('spatial-wall-depth').textContent=state.blocked?state.wallDistance.toFixed(2)+' m':'—';$('spatial-explanation').textContent=state.blocked?c.blockedNote:c.clearNote;}
  function setPosition(t){state=SpatialSceneModel.state(t,Number(frequency.value));updateReadouts();updateAudio();requestDraw();}
  function project(p){const x=p[0]*Math.cos(yaw)-p[2]*Math.sin(yaw),z=p[0]*Math.sin(yaw)+p[2]*Math.cos(yaw),y=p[1]-.65;const vertical=y*Math.cos(pitch)-z*Math.sin(pitch),depth=y*Math.sin(pitch)+z*Math.cos(pitch),perspective=15/(15-depth),scale=Math.min(w/13.8,h/8.9);return [w*.5+x*scale*perspective,h*.47-vertical*scale*perspective];}
  function line(points,color,width=1,dash=[]){ctx.beginPath();points.map(project).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
  function polygon(points,fill,stroke){ctx.beginPath();points.map(project).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
  function dot(p,color,r=4){const q=project(p);ctx.beginPath();ctx.arc(q[0],q[1],r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
  function label(p,text,color,dx=12,dy=-12){const q=project(p);ctx.font='12px ui-monospace,monospace';ctx.fillStyle='#0d1118';const tw=ctx.measureText(text).width;let x=Math.min(w-tw-10,Math.max(10,q[0]+dx)),y=Math.max(18,q[1]+dy);ctx.fillRect(x-5,y-13,tw+10,19);ctx.fillStyle=color;ctx.fillText(text,x,y);}
  function node(p,color,text){line([[p[0],0,p[2]],p],color+'65',1,[3,5]);dot([p[0],0,p[2]],color+'75',3);const q=project(p);ctx.beginPath();ctx.arc(q[0],q[1],12,0,Math.PI*2);ctx.fillStyle=color+'18';ctx.fill();ctx.strokeStyle=color+'80';ctx.stroke();dot(p,color,5);label(p,text,color);}
  function arrow(points,color){const a=project(SpatialSceneModel.pointOnPath(points,.85)),b=project(SpatialSceneModel.pointOnPath(points,.91)),angle=Math.atan2(b[1]-a[1],b[0]-a[0]);ctx.beginPath();ctx.moveTo(...b);ctx.lineTo(b[0]-9*Math.cos(angle-.4),b[1]-9*Math.sin(angle-.4));ctx.moveTo(...b);ctx.lineTo(b[0]-9*Math.cos(angle+.4),b[1]-9*Math.sin(angle+.4));ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.stroke();}
  function pulses(points,color,gain,phase){const count=Math.max(3,Math.min(12,Math.round(SpatialSceneModel.length(points)/state.wavelength)));ctx.globalAlpha=Math.max(.2,Math.min(1,gain*1.5));for(let i=0;i<count;i++)dot(SpatialSceneModel.pointOnPath(points,(phase+i/count)%1),color,2.5);ctx.globalAlpha=1;}
  function draw(now){ctx.clearRect(0,0,w,h);const c=copy[lang];polygon([[-5,0,-5.8],[5,0,-5.8],[5,0,5.8],[-5,0,5.8]],'#121923','#2a3545');for(let x=-5;x<=5;x++)line([[x,0,-5.8],[x,0,5.8]],'#202b3a');for(let z=-5;z<=5;z++)line([[-5,0,z],[5,0,z]],'#202b3a');
    // Listener rail and faint reference planes make depth legible without enclosing the scene.
    line([[3,.01,-4.8],[3,.01,4.8]],'#8094b448',1.4,[3,5]);
    for(const z of [-4.8,0,4.8])dot([3,.02,z],'#53627c',2);
    const a=.13,l=state.wall.halfLength,H=state.wall.height;
    const faces=[{points:[[-a,0,-l],[-a,H,-l],[-a,H,l],[-a,0,l]],color:'#53688542'}, {points:[[a,0,-l],[a,H,-l],[a,H,l],[a,0,l]],color:'#7792b738'},{points:[[-a,H,-l],[a,H,-l],[a,H,l],[-a,H,l]],color:'#9bb1cc55'},{points:[[-a,0,-l],[a,0,-l],[a,H,-l],[-a,H,-l]],color:'#61758d55'},{points:[[-a,0,l],[a,0,l],[a,H,l],[-a,H,l]],color:'#61758d55'}];
    faces.sort((u,v)=>project(u.points[0])[1]-project(v.points[0])[1]).forEach(f=>polygon(f.points,f.color,'#7e96b880'));
    label([0,H,0],c.wall,'#9aadc6',10,-18);
    const phase=reduced.matches?0:audio?(now/1000*.6)%1:(state.progress*2)%1;
    if(state.blocked){
      for(const candidate of state.candidates.slice(1))line(candidate.points,'#70d6b72a',1,[3,5]);
      line(state.diffraction.points,'#70d6b726',7);line(state.diffraction.points,'#70d6b7',2);arrow(state.diffraction.points,'#70d6b7');dot(state.diffraction.points[1],'#70d6b7',4);
      line(state.transmitted.points,'#cf98c8aa',1.7,[5,6]);pulses(state.transmitted.points,'#cf98c8',state.transmitted.gain,phase);pulses(state.diffraction.points,'#70d6b7',state.diffracted.gain,phase);
      line(state.reflection.points,'#e9b777',1.5);arrow(state.reflection.points,'#e9b777');dot(state.hit,'#e9b777',5);pulses(state.reflection.points,'#e9b777',.6,phase);
      const entry=SpatialSceneModel.mix(state.source,state.listener,(3-a)/6),exit=SpatialSceneModel.mix(state.source,state.listener,(3+a)/6);line([entry,exit],'#efc0e9',4);
    }else{line([state.source,state.listener],'#7b9aff28',7);line([state.source,state.listener],'#7b9aff',2);arrow([state.source,state.listener],'#7b9aff');pulses([state.source,state.listener],'#a2b9ff',state.transmitted.gain,phase);}
    node(state.source,'#7b9aff',c.source);node(state.listener,'#eef2fb',c.listener);
    ctx.fillStyle='#7e8fa9';ctx.font='10px ui-monospace,monospace';ctx.fillText('3D / 1 m',18,25);lastDraw=now;dirty=false;
  }
  function tick(now){raf=0;if(!visible||document.hidden)return;if(dirty||(audio&&!reduced.matches&&now-lastDraw>=33))draw(now);if(audio&&!reduced.matches)raf=requestAnimationFrame(tick);}
  function requestDraw(){dirty=true;if(visible&&!raf&&!document.hidden)raf=requestAnimationFrame(tick);}
  function resize(){const top=document.querySelector('header').getBoundingClientRect().height+10;root.style.setProperty('--spatial-top',top+'px');const panel=root.querySelector('.spatial-panel'),old=canvas.getBoundingClientRect(),other=panel.getBoundingClientRect().height-old.height;root.style.setProperty('--spatial-stage-height',Math.max(180,Math.min(old.width<560?250:420,window.innerHeight-top-other-20))+'px');const rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio||1,1.75);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);requestDraw();}
  function updateAudio(){if(!audio)return;const now=audio.context.currentTime;audio.oscillators.forEach((o,i)=>o.frequency.setTargetAtTime(state.frequency*(i+1),now,.04));for(const [branch,path] of [[audio.direct,state.transmitted],[audio.diffraction,state.diffracted]]){branch.gain.gain.setTargetAtTime(path.gain,now,.05);branch.filter.frequency.setTargetAtTime(path.cutoff,now,.05);branch.delay.delayTime.setTargetAtTime(path.delay,now,.08);branch.pan.pan.setTargetAtTime(path.pan,now,.05);}}
  function stopAudio(){audioGeneration++;if(audio){const old=audio;audio=null;old.master.gain.setTargetAtTime(0,old.context.currentTime,.015);old.oscillators.forEach(o=>{try{o.stop(old.context.currentTime+.09);}catch{}});setTimeout(()=>old.context.close().catch(()=>{}),140);}updateReadouts();requestDraw();}
  async function startAudio(){const generation=++audioGeneration;let context;
    try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('Audio unavailable');context=new Audio({latencyHint:'interactive'});await context.resume();if(generation!==audioGeneration||!visible||document.hidden){await context.close();return;}
      const master=context.createGain();master.gain.value=0;master.connect(context.destination);const mixer=context.createGain();mixer.gain.value=.065;
      const makeBranch=()=>{const filter=context.createBiquadFilter();filter.type='lowpass';filter.Q.value=.65;const delay=context.createDelay(.2),gain=context.createGain(),pan=context.createStereoPanner();mixer.connect(filter);filter.connect(delay);delay.connect(gain);gain.connect(pan);pan.connect(master);return{filter,delay,gain,pan};};
      const direct=makeBranch(),diffraction=makeBranch(),oscillators=[1,.4,.2,.12].map((amplitude,i)=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=state.frequency*(i+1);gain.gain.value=amplitude;oscillator.connect(gain);gain.connect(mixer);oscillator.start();return oscillator;});
      audio={context,master,direct,diffraction,oscillators};audioError=false;updateAudio();master.gain.setTargetAtTime(.4,context.currentTime,.08);updateReadouts();requestDraw();
    }catch{if(context)context.close().catch(()=>{});if(generation===audioGeneration){audioError=true;updateReadouts();}}
  }
  button.addEventListener('click',()=>audio?stopAudio():startAudio());
  const cancelPendingScroll=()=>{if(scrollRaf)cancelAnimationFrame(scrollRaf);scrollRaf=0;};
  position.addEventListener('input',()=>{manualPosition=true;cancelPendingScroll();setPosition(Number(position.value)/100);});frequency.addEventListener('input',()=>{cancelPendingScroll();setPosition(state.progress);});
  let scrollRaf=0;
  function onScroll(){if(scrollRaf)return;scrollRaf=requestAnimationFrame(()=>{scrollRaf=0;if(!visible||reduced.matches||manualPosition)return;const track=root.querySelector('.spatial-scroll'),panel=root.querySelector('.spatial-panel'),rect=track.getBoundingClientRect(),top=parseFloat(getComputedStyle(panel).top)||0,span=track.offsetHeight-panel.offsetHeight;if(span>0)setPosition(Math.max(0,Math.min(1,(top-rect.top)/span)));});}
  for(const name of ['wheel','touchmove'])window.addEventListener(name,()=>{manualPosition=false;onScroll();},{passive:true});
  window.addEventListener('keydown',event=>{if(['PageDown','PageUp',' '].includes(event.key)&&!event.target.matches('input,button')){manualPosition=false;onScroll();}});
  window.addEventListener('pointerdown',event=>{if(!root.contains(event.target)){manualPosition=false;}});
  window.addEventListener('scroll',onScroll,{passive:true});
  const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible){resize();onScroll();requestDraw();}else{if(audio)stopAudio();audioGeneration++;if(raf)cancelAnimationFrame(raf);raf=0;}},{threshold:.02});observer.observe(root.querySelector('.spatial-panel'));
  let resizeRaf=0;
  const queueResize=()=>{if(!resizeRaf)resizeRaf=requestAnimationFrame(()=>{resizeRaf=0;resize();});};
  new ResizeObserver(queueResize).observe(canvas);
  window.addEventListener('resize',queueResize,{passive:true});
  new MutationObserver(updateCopy).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  canvas.addEventListener('pointerdown',event=>{drag={x:event.clientX,y:event.clientY,yaw,pitch};if(event.pointerType==='mouse')canvas.setPointerCapture(event.pointerId);});
  canvas.addEventListener('pointermove',event=>{if(!drag)return;yaw=drag.yaw+(event.clientX-drag.x)*.006;if(event.pointerType==='mouse')pitch=Math.max(.35,Math.min(1.05,drag.pitch+(event.clientY-drag.y)*.004));requestDraw();});
  for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>drag=null);
  canvas.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();manualPosition=true;cancelPendingScroll();setPosition(event.key==='Home'?0:event.key==='End'?1:state.progress+(['ArrowRight','ArrowUp'].includes(event.key)?1:-1)*.02);}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();if(raf)cancelAnimationFrame(raf);raf=0;}else requestDraw();});window.addEventListener('pagehide',stopAudio);
  reduced.addEventListener('change',()=>{onScroll();requestDraw();});updateCopy();resize();
})();
